version: '3'

services:
  minio:
    image: bitnami/minio:latest
    #command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - my_network
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
      - api_data:/app/data
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - minio


networks:
  my_network:
    driver: bridge

volumes:
  api_data:
  minio_data:
    driver: local
